/**
 * This file was automatically generated by the Mule Development Kit
 */
package com.mulesoft.module.indivo;

import org.mule.api.MuleEvent;
import org.mule.construct.Flow;
import org.mule.tck.FunctionalTestCase;
import org.mule.tck.AbstractMuleTestCase;

import org.junit.Test;

public class IndivoModuleTest extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return "mule-config.xml";
    }

    @Test
    public void testIndivo() throws Exception
    {
    }

}
